name: BedrockPlayerSupport
version: '${project.version}'
main: cn.dsnbo.bedrockplayersupport.BedrockPlayerSupport
api-version: 1.13
depend:
  - floodgate
softdepend:
  - CMI
  - Essentials
  - AuthMe
  - CatSeedLogin
  - NexAuth
authors: [ DongShaoNB ]
description: Support bedrock player fast use java plugin
website: www.dsnbo.cn

commands:
  tpagui:
    description: "Bedrock player teleport menu"
  tpaheregui:
    description: "Bedrock player teleport here menu"
